spring:
  datasource:
    url: jdbc:h2:mem:aws-s3
    username: admin
    password: 123456
    platform: h2

  h2:
    console:
      enabled: true
      path: /h2-console

amazonProperties:
  endpointUrl: ${ENDPOINT_URL}
  accessKey: ${ACCESS_KEY}
  secretKey: ${SECRET_KEY}
  bucketName: ${BUCKET_NAME}